//! Integration tests: parse OMML fixture docx files end-to-end.
//!
//! These .docx files are generated by tools/metrics/gen_omml_fixtures.py
//! and each contains one <m:oMathPara> with a minimal OMML primitive.
//!
//! Verifies that parser::parse_docx correctly produces a Block::Math
//! entry in the page's block list when encountering OMML content.

use std::fs;

use oxidocs_core::parser::parse_docx;
use oxidocs_core::ir::{Block, MathBlock, MathExpr, FracBarType};

fn fixture_path(name: &str) -> std::path::PathBuf {
    // Tests run with CWD at the crate root; fixtures are two levels up.
    let crate_root = std::env::current_dir().unwrap();
    let workspace_root = crate_root.parent().unwrap().parent().unwrap();
    workspace_root.join("tools").join("fixtures").join("omml_samples").join(name)
}

fn count_math_blocks(doc: &oxidocs_core::ir::Document) -> usize {
    doc.pages.iter()
        .flat_map(|p| p.blocks.iter())
        .filter(|b| matches!(b, Block::Math(_)))
        .count()
}

fn find_first_math(doc: &oxidocs_core::ir::Document) -> Option<&MathBlock> {
    doc.pages.iter()
        .flat_map(|p| p.blocks.iter())
        .find_map(|b| if let Block::Math(mb) = b { Some(mb) } else { None })
}

#[test]
fn fixture_01_frac_produces_math_block() {
    let path = fixture_path("01_frac.docx");
    if !path.exists() {
        eprintln!("skipping: {} not found (regenerate via gen_omml_fixtures.py)",
                  path.display());
        return;
    }
    let data = fs::read(&path).expect("read fixture");
    let doc = parse_docx(&data).expect("parse fixture");

    assert_eq!(count_math_blocks(&doc), 1, "expected 1 Block::Math");

    let mb = find_first_math(&doc).expect("found no Math block");
    match mb {
        MathBlock::Display { content, .. } => {
            assert_eq!(content.len(), 1);
            match &content[0] {
                MathExpr::Fraction { num, den, bar_type } => {
                    assert!(matches!(**num, MathExpr::Text(ref s) if s == "a"));
                    assert!(matches!(**den, MathExpr::Text(ref s) if s == "b"));
                    assert_eq!(*bar_type, FracBarType::Bar);
                }
                other => panic!("expected Fraction, got {:?}", other),
            }
        }
        MathBlock::Inline(_) => panic!("expected Display, got Inline"),
    }
}

#[test]
fn fixture_02_sup_produces_superscript() {
    let path = fixture_path("02_sup.docx");
    if !path.exists() { return; }
    let data = fs::read(&path).unwrap();
    let doc = parse_docx(&data).unwrap();
    let mb = find_first_math(&doc).expect("no Math block");
    let content = match mb {
        MathBlock::Display { content, .. } => content,
        _ => panic!(),
    };
    match &content[0] {
        MathExpr::Superscript { base, sup } => {
            assert!(matches!(**base, MathExpr::Text(ref s) if s == "x"));
            assert!(matches!(**sup, MathExpr::Text(ref s) if s == "2"));
        }
        _ => panic!("expected Superscript"),
    }
}

#[test]
fn fixture_03_sub_produces_subscript() {
    let path = fixture_path("03_sub.docx");
    if !path.exists() { return; }
    let data = fs::read(&path).unwrap();
    let doc = parse_docx(&data).unwrap();
    let mb = find_first_math(&doc).expect("no Math block");
    let content = match mb {
        MathBlock::Display { content, .. } => content,
        _ => panic!(),
    };
    match &content[0] {
        MathExpr::Subscript { base, sub } => {
            assert!(matches!(**base, MathExpr::Text(ref s) if s == "x"));
            assert!(matches!(**sub, MathExpr::Text(ref s) if s == "1"));
        }
        _ => panic!("expected Subscript"),
    }
}

#[test]
fn fixture_04_sqrt_produces_radical() {
    let path = fixture_path("04_sqrt.docx");
    if !path.exists() { return; }
    let data = fs::read(&path).unwrap();
    let doc = parse_docx(&data).unwrap();
    let mb = find_first_math(&doc).expect("no Math block");
    let content = match mb {
        MathBlock::Display { content, .. } => content,
        _ => panic!(),
    };
    match &content[0] {
        MathExpr::Radical { degree, radicand } => {
            assert!(degree.is_none(), "sqrt should have no degree");
            assert!(matches!(**radicand, MathExpr::Text(ref s) if s == "x"));
        }
        _ => panic!("expected Radical"),
    }
}

#[test]
fn all_ten_fixtures_parse_without_error() {
    for name in [
        "01_frac.docx", "02_sup.docx", "03_sub.docx", "04_sqrt.docx",
        "05_nary_sum.docx", "06_matrix_2x2.docx", "07_acc_hat.docx",
        "08_box.docx", "09_bar.docx", "10_limit.docx",
    ] {
        let path = fixture_path(name);
        if !path.exists() {
            eprintln!("skipping {}", name);
            continue;
        }
        let data = fs::read(&path).unwrap();
        let doc = parse_docx(&data).unwrap_or_else(|e| {
            panic!("failed to parse {}: {:?}", name, e)
        });
        // Each fixture has exactly 1 oMathPara.
        assert_eq!(count_math_blocks(&doc), 1,
            "{} should produce exactly 1 Block::Math", name);
    }
}
