"""
Measure numbered-list fixtures.

For each paragraph in each fixture:
  - x_text = position of first character of paragraph text
  - x_start = position of paragraph (incl. number marker, hopefully)
  - text content (verify Word rendered the marker)

The marker is auto-generated by Word; it doesn't appear in the run text.
But COM Selection.Information may give marker position via Find on first
glyph of "Item" (the body text).
"""
import os
import json
import time
import glob

import win32com.client
import pythoncom

OUT_DIR = os.path.join(os.path.dirname(__file__), "output")
FIX_DIR = os.path.join(OUT_DIR, "numbered_list_fixtures")
OUT_JSON = os.path.join(OUT_DIR, "ra2_numbered_list.json")


RPC_REJECTED_CODES = {-2147418111, -2147023174, -2147023170}

def retry(fn, *args, retries=15, delay=0.3, **kwargs):
    last_exc = None
    for i in range(retries):
        try:
            return fn(*args, **kwargs)
        except Exception as e:
            last_exc = e
            code = e.args[0] if hasattr(e, "args") and len(e.args) >= 1 else None
            if code in RPC_REJECTED_CODES or "rejected" in str(e).lower():
                pythoncom.PumpWaitingMessages()
                time.sleep(delay * (1.3 ** i))
                continue
            raise
    raise last_exc


def measure(word, path):
    wdoc = retry(lambda: word.Documents.Open(path))
    try:
        wdoc.Repaginate()
        time.sleep(0.05)
        paras = []
        for i in range(1, wdoc.Paragraphs.Count + 1):
            p = wdoc.Paragraphs(i)
            text = p.Range.Text.strip()
            list_text = ""
            try:
                # ListFormat.ListString returns the rendered marker (e.g. "1.", "(2)")
                list_text = p.Range.ListFormat.ListString
            except Exception:
                pass

            # Find position of "Item" (first body word) in the paragraph
            try:
                idx = text.find("Item")
                if idx >= 0:
                    sub = wdoc.Range(p.Range.Start + idx,
                                     p.Range.Start + idx + 1)
                    text_x = round(sub.Information(5), 4)
                else:
                    text_x = None
            except Exception:
                text_x = None

            # Para start (= marker position)
            para_x = round(p.Range.Information(5), 4)
            para_y = round(p.Range.Information(6), 4)

            paras.append({
                "i": i,
                "text": text[:60],
                "list_marker": list_text,
                "para_x": para_x,
                "text_x_after_marker": text_x,
                "y": para_y,
            })
        return {
            "path": os.path.basename(path),
            "paragraphs": paras,
        }
    finally:
        wdoc.Close(False)


def main():
    word = win32com.client.gencache.EnsureDispatch("Word.Application")
    word.Visible = False
    word.DisplayAlerts = False
    time.sleep(2.0)
    try:
        retry(lambda: word.Documents.Count)
    except Exception:
        pass

    paths = sorted(glob.glob(os.path.join(FIX_DIR, "*.docx")))
    print(f"Measuring {len(paths)} fixtures from {FIX_DIR}")

    results = []
    try:
        for p in paths:
            try:
                r = measure(word, p)
                results.append(r)
                print(f"\n  {os.path.basename(p)}")
                for para in r["paragraphs"][:6]:
                    print(f"    P{para['i']:2}: marker='{para['list_marker']:6s}' "
                          f"para_x={para['para_x']} text_x={para['text_x_after_marker']} "
                          f"y={para['y']} text='{para['text']}'")
                if len(r["paragraphs"]) > 6:
                    last = r["paragraphs"][-1]
                    print(f"    ...")
                    print(f"    P{last['i']:2}: marker='{last['list_marker']:6s}' "
                          f"para_x={last['para_x']} text_x={last['text_x_after_marker']} "
                          f"y={last['y']} text='{last['text']}'")
            except Exception as e:
                print(f"  ERR {os.path.basename(p)}: {e}")
    finally:
        with open(OUT_JSON, "w", encoding="utf-8") as f:
            json.dump(results, f, indent=2, ensure_ascii=False)
        print(f"\nSaved {len(results)} records to {OUT_JSON}")
        try:
            word.Quit()
        except Exception as e:
            print(f"  (word.Quit failed: {e})")


if __name__ == "__main__":
    main()
