use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Raw metrics data as generated by tools/font-metrics-gen.
/// Widths are keyed by codepoint (u32) and stored in font units.
#[derive(Debug, Clone, Deserialize)]
struct RawFontMetrics {
    family: String,
    units_per_em: u16,
    ascender: i16,
    descender: i16,
    line_gap: i16,
    #[serde(default)]
    win_ascent: u16,
    #[serde(default)]
    win_descent: u16,
    #[serde(default)]
    typo_ascender: i16,
    #[serde(default)]
    typo_descender: i16,
    #[serde(default)]
    typo_line_gap: i16,
    widths: HashMap<u32, u16>,
}

/// Per-character font metrics normalized to 1em.
/// All widths are expressed as a fraction of the em-square.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FontMetrics {
    pub family: String,
    /// hhea ascent normalized to 1em
    pub ascent: f32,
    /// hhea descent normalized to 1em (positive value)
    pub descent: f32,
    /// hhea line gap normalized to 1em
    pub line_gap: f32,
    /// OS/2 usWinAscent normalized to 1em
    pub win_ascent: f32,
    /// OS/2 usWinDescent normalized to 1em (positive value)
    pub win_descent: f32,
    /// OS/2 sTypoAscender normalized to 1em
    pub typo_ascent: f32,
    /// OS/2 |sTypoDescender| normalized to 1em (positive value)
    pub typo_descent: f32,
    /// OS/2 sTypoLineGap normalized to 1em
    pub typo_line_gap: f32,
    /// Per-character advance widths, normalized to 1em.
    pub char_widths: HashMap<char, f32>,
}

impl FontMetrics {
    /// Look up the advance width for a character (normalized to 1em).
    /// Falls back to fullwidth/halfwidth heuristics for unmeasured chars.
    pub fn char_width_em(&self, c: char) -> f32 {
        self.char_widths.get(&c).copied().unwrap_or_else(|| {
            if is_halfwidth_katakana(c) {
                0.5
            } else if is_fullwidth(c) {
                1.0
            } else {
                0.5
            }
        })
    }

    /// Character width in points at a given font size.
    pub fn char_width_pt(&self, c: char, font_size: f32) -> f32 {
        self.char_width_em(c) * font_size
    }

    /// Simple line height in points (no GDI rounding).
    /// Uses max(win, hhea) metrics normalized to 1em.
    pub fn line_height_pt(&self, font_size: f32) -> f32 {
        self.line_height_ratio() * font_size
    }

    /// The font's line height as a ratio of 1em.
    /// max(win, hhea) metrics — the raw font line height before any
    /// paragraph-level minimums or spacing multipliers.
    pub fn line_height_ratio(&self) -> f32 {
        let win_height = self.win_ascent + self.win_descent;
        let hhea_height = self.ascent + self.descent + self.line_gap;
        win_height.max(hhea_height)
    }

    /// GDI TEXTMETRIC-style line height simulation.
    ///
    /// Word uses Windows GDI integer rounding internally. This simulates
    /// that rounding at a given DPI to match Word's exact line height values.
    /// Empirically, DPI=150 gives the best match against Word COM measurements
    /// (avg error 0.24pt, 30/32 test cases within 0.5pt).
    pub fn gdi_line_height(&self, font_size: f32, dpi: f32) -> f32 {
        let ppem = (font_size * dpi / 72.0).round();

        // OS/2 win metrics path: tmAscent + tmDescent
        let win_asc_px = (self.win_ascent * ppem).ceil();
        let win_desc_px = (self.win_descent * ppem).ceil();
        let win_height = (win_asc_px + win_desc_px) * 72.0 / dpi;

        // hhea metrics path: includes line_gap as external leading
        let hhea_asc_px = (self.ascent * ppem).ceil();
        let hhea_desc_px = (self.descent * ppem).ceil();
        let hhea_gap_px = (self.line_gap * ppem).ceil();
        let hhea_height = (hhea_asc_px + hhea_desc_px + hhea_gap_px) * 72.0 / dpi;

        win_height.max(hhea_height)
    }
}

/// Registry of font metrics for multiple font families.
/// Backed by real measurements extracted from Windows system fonts.
pub struct FontMetricsRegistry {
    fonts: HashMap<String, FontMetrics>,
    default_family: String,
}

impl FontMetricsRegistry {
    /// Load the embedded font metrics data (generated by tools/font-metrics-gen).
    pub fn load() -> Self {
        let raw_json = include_str!("data/font_metrics_compact.json");
        let raw_list: Vec<RawFontMetrics> =
            serde_json::from_str(raw_json).expect("embedded font metrics should be valid JSON");

        let mut fonts = HashMap::new();

        for raw in raw_list {
            let upm = raw.units_per_em as f32;
            let ascent = raw.ascender as f32 / upm;
            let descent = (-raw.descender) as f32 / upm; // descender is negative in fonts
            let line_gap = raw.line_gap.max(0) as f32 / upm;

            // OS/2 win metrics (fall back to hhea if not present)
            let win_ascent = if raw.win_ascent > 0 {
                raw.win_ascent as f32 / upm
            } else {
                ascent
            };
            let win_descent = if raw.win_descent > 0 {
                raw.win_descent as f32 / upm
            } else {
                descent
            };
            let typo_ascent = if raw.typo_ascender != 0 {
                raw.typo_ascender as f32 / upm
            } else {
                ascent
            };
            let typo_descent = (-raw.typo_descender).max(0) as f32 / upm;
            let typo_line_gap = raw.typo_line_gap.max(0) as f32 / upm;

            let mut char_widths = HashMap::new();
            for (&codepoint, &advance) in &raw.widths {
                if let Some(c) = char::from_u32(codepoint) {
                    char_widths.insert(c, advance as f32 / upm);
                }
            }

            let metrics = FontMetrics {
                family: raw.family.clone(),
                ascent,
                descent,
                line_gap,
                win_ascent,
                win_descent,
                typo_ascent,
                typo_descent,
                typo_line_gap,
                char_widths,
            };

            // Store under exact name
            fonts.insert(raw.family.clone(), metrics.clone());

            // Also store under base family name (without "Bold", "Regular", etc.)
            // so lookup by "Calibri" finds "Calibri" even if only "Calibri Bold" was stored
            let base = base_family_name(&raw.family);
            if base != raw.family {
                fonts.entry(base).or_insert(metrics);
            }
        }

        Self {
            fonts,
            default_family: "Calibri".to_string(),
        }
    }

    /// Get metrics for a font family. Falls back to default (Calibri) if not found.
    pub fn get(&self, family: &str) -> &FontMetrics {
        // Try exact match first
        if let Some(m) = self.fonts.get(family) {
            return m;
        }
        // Try normalized name
        let normalized = normalize_family_name(family);
        if let Some(m) = self.fonts.get(&normalized) {
            return m;
        }
        // Try base name
        let base = base_family_name(family);
        if let Some(m) = self.fonts.get(&base) {
            return m;
        }
        // Fallback to default
        self.fonts.get(&self.default_family).unwrap_or_else(|| {
            self.fonts.values().next().expect("FontMetricsRegistry has no fonts loaded")
        })
    }

    /// Get the default font metrics (Calibri).
    pub fn default_metrics(&self) -> &FontMetrics {
        self.get(&self.default_family)
    }
}

/// Strip weight/style suffixes to get the base family name.
fn base_family_name(name: &str) -> String {
    let suffixes = [
        " Bold", " Regular", " Demibold", " Light", " Medium",
        " Italic", " Oblique", " Thin", " Black", " Heavy",
    ];
    let mut result = name.to_string();
    for suffix in &suffixes {
        if let Some(stripped) = result.strip_suffix(suffix) {
            result = stripped.to_string();
        }
    }
    result
}

/// Normalize common font family name aliases used in OOXML.
fn normalize_family_name(name: &str) -> String {
    match name {
        "ＭＳ ゴシック" | "MS ゴシック" | "ＭＳ Gothic" => "MS Gothic".to_string(),
        "ＭＳ 明朝" | "MS 明朝" | "ＭＳ Mincho" => "MS Mincho".to_string(),
        "游ゴシック" | "Yu Gothic UI" => "Yu Gothic Regular".to_string(),
        "游明朝" => "Yu Mincho Regular".to_string(),
        _ => name.to_string(),
    }
}

/// Half-width katakana: U+FF65..U+FF9F (ｦ, ｧ, ｨ, ... ﾝ, ﾞ, ﾟ)
fn is_halfwidth_katakana(ch: char) -> bool {
    matches!(ch as u32, 0xFF65..=0xFF9F)
}

fn is_fullwidth(ch: char) -> bool {
    matches!(ch as u32,
        0x3000..=0x303F |  // CJK Symbols and Punctuation
        0x3040..=0x309F |  // Hiragana
        0x30A0..=0x30FF |  // Katakana (full-width)
        0x3400..=0x4DBF |  // CJK Unified Ideographs Extension A
        0x4E00..=0x9FFF |  // CJK Unified Ideographs
        0xF900..=0xFAFF |  // CJK Compatibility Ideographs
        0xFF01..=0xFF60 |  // Fullwidth Latin / symbols
        0xFFE0..=0xFFE6 |  // Fullwidth currency/symbols
        0x20000..=0x2A6DF  // CJK Unified Ideographs Extension B
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_loads() {
        let reg = FontMetricsRegistry::load();
        let calibri = reg.get("Calibri");
        assert_eq!(calibri.family, "Calibri");
        // Calibri space should be ~0.226em (463/2048)
        let space_w = calibri.char_width_em(' ');
        assert!(space_w > 0.2 && space_w < 0.3, "space width: {}", space_w);
    }

    #[test]
    fn test_japanese_font_lookup() {
        let reg = FontMetricsRegistry::load();
        let yu = reg.get("Yu Gothic Regular");
        assert!(yu.family.contains("Yu Gothic"));
        // CJK char should be ~1.0em
        let kanji_w = yu.char_width_em('漢');
        assert!(kanji_w > 0.9 && kanji_w < 1.1, "kanji width: {}", kanji_w);
    }

    #[test]
    fn test_family_alias() {
        let reg = FontMetricsRegistry::load();
        let ms = reg.get("ＭＳ ゴシック");
        assert!(ms.family.contains("MS Gothic") || ms.family.contains("Calibri"));
    }

    #[test]
    fn test_fallback_to_default() {
        let reg = FontMetricsRegistry::load();
        let unknown = reg.get("NonexistentFont");
        assert_eq!(unknown.family, "Calibri");
    }

    #[test]
    fn test_gdi_line_height_vs_word_com() {
        // Word COM measured line gaps (single spacing, no grid).
        // Formula: max(gdi(run_font, size, 150), gdi(default_font, size, 150))
        // Expected: avg error < 0.5pt, all within 1.0pt.
        let reg = FontMetricsRegistry::load();
        let default_metrics = reg.default_metrics();
        const DPI: f32 = 150.0;

        // (font_family, font_size, word_com_gap)
        let test_cases: Vec<(&str, f32, f32)> = vec![
            ("Calibri", 10.5, 13.45),
            ("Calibri", 11.0, 14.00),
            ("Calibri", 12.0, 15.55),
            ("Calibri", 14.0, 17.70),
            ("Arial", 10.5, 13.45),
            ("Arial", 14.0, 17.70),
            ("Times New Roman", 12.0, 15.55),
            ("MS Gothic", 10.5, 13.45),
            ("MS Gothic", 14.0, 18.25),
            ("Yu Gothic Regular", 10.5, 17.70),
            ("Yu Gothic Regular", 11.0, 18.25),
            ("Yu Gothic Regular", 12.0, 19.90),
            ("Yu Gothic Regular", 14.0, 23.65),
        ];

        let mut total_err = 0.0_f32;
        let mut max_err = 0.0_f32;

        for (family, size, com_gap) in &test_cases {
            let m = reg.get(family);
            let run_h = m.gdi_line_height(*size, DPI);
            let def_h = default_metrics.gdi_line_height(*size, DPI);
            let predicted = run_h.max(def_h);
            let err = (predicted - com_gap).abs();
            total_err += err;
            max_err = max_err.max(err);
            assert!(
                err < 1.0,
                "{} {}pt: predicted={:.2}, COM={:.2}, err={:.2}",
                family, size, predicted, com_gap, err
            );
        }

        let avg_err = total_err / test_cases.len() as f32;
        assert!(avg_err < 0.5, "avg error {:.3}pt exceeds 0.5pt", avg_err);
    }
}
