use serde::{Deserialize, Serialize};
use std::collections::HashMap;

fn default_upm() -> u16 { 2048 }

/// Pixel-rounded multiplication matching Word's font metrics.
/// All font metric values are pre-normalized to [0,1] range (÷UPM),
/// so this is simply `round(value * ppem)`.
fn pixel_round(value_normalized: f32, ppem: f32) -> f32 {
    (value_normalized * ppem).round()
}

/// Raw metrics data as generated by tools/font-metrics-gen.
/// Widths are keyed by codepoint (u32) and stored in font units.
#[derive(Debug, Clone, Deserialize)]
struct RawFontMetrics {
    family: String,
    units_per_em: u16,
    ascender: i16,
    descender: i16,
    line_gap: i16,
    #[serde(default)]
    win_ascent: u16,
    #[serde(default)]
    win_descent: u16,
    #[serde(default)]
    typo_ascender: i16,
    #[serde(default)]
    typo_descender: i16,
    #[serde(default)]
    typo_line_gap: i16,
    widths: HashMap<u32, u16>,
}

/// Per-character font metrics normalized to 1em.
/// All widths are expressed as a fraction of the em-square.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FontMetrics {
    pub family: String,
    /// Units per em (e.g. 256 for MS Gothic/Mincho, 2048 for most others)
    #[serde(default = "default_upm")]
    pub units_per_em: u16,
    /// hhea ascent normalized to 1em
    pub ascent: f32,
    /// hhea descent normalized to 1em (positive value)
    pub descent: f32,
    /// hhea line gap normalized to 1em
    pub line_gap: f32,
    /// OS/2 usWinAscent normalized to 1em
    pub win_ascent: f32,
    /// OS/2 usWinDescent normalized to 1em (positive value)
    pub win_descent: f32,
    /// OS/2 sTypoAscender normalized to 1em
    pub typo_ascent: f32,
    /// OS/2 |sTypoDescender| normalized to 1em (positive value)
    pub typo_descent: f32,
    /// OS/2 sTypoLineGap normalized to 1em
    pub typo_line_gap: f32,
    /// Per-character advance widths, normalized to 1em.
    pub char_widths: HashMap<char, f32>,
}

impl FontMetrics {
    /// Look up the advance width for a character (normalized to 1em).
    /// Falls back to fullwidth/halfwidth heuristics for unmeasured chars.
    pub fn char_width_em(&self, c: char) -> f32 {
        self.char_widths.get(&c).copied().unwrap_or_else(|| {
            if is_halfwidth_katakana(c) {
                0.5
            } else if is_fullwidth(c) {
                1.0
            } else {
                0.5
            }
        })
    }

    /// Character width in points at a given font size.
    ///
    /// Word uses GDI pixel-grid snapping for character placement:
    ///   ppem = round(fontSize_pt * 96 / 72)
    ///   char_width_px = round(advance_em * ppem)
    ///   char_width_pt = char_width_px * 72 / 96
    ///
    /// For CJK monospace fonts (UPM=256: MS Gothic/Mincho), fullwidth characters
    /// use even-pixel rounding: ceil_even(ppem). GDI-measured 2026-03-29.
    /// This matters at small font sizes (7-10pt) where ppem is odd.
    pub fn char_width_pt(&self, c: char, font_size: f32) -> f32 {
        let ppem = (font_size * 96.0 / 72.0).round();
        let advance_em = self.char_width_em(c);

        // CJK monospace fonts (UPM=256): COM confirmed — fullwidth = fontSize, halfwidth = fontSize/2
        // No GDI pixel rounding; Word uses the point value directly.
        if self.units_per_em == 256 && is_fullwidth(c) {
            return font_size;
        }
        if self.units_per_em == 256 && (is_halfwidth_katakana(c) || advance_em <= 0.51) {
            return font_size / 2.0;
        }

        (advance_em * ppem).round() * 72.0 / 96.0
    }

    /// Simple line height in points (no pixel rounding).
    /// Uses max(win, hhea) metrics normalized to 1em.
    pub fn line_height_pt(&self, font_size: f32) -> f32 {
        self.line_height_ratio() * font_size
    }

    /// The font's line height as a ratio of 1em.
    /// max(win, hhea) metrics — the raw font line height before any
    /// paragraph-level minimums or spacing multipliers.
    pub fn line_height_ratio(&self) -> f32 {
        let win_height = self.win_ascent + self.win_descent;
        let hhea_height = self.ascent + self.descent + self.line_gap;
        win_height.max(hhea_height)
    }

    /// Line height calculation matching Word's behavior.
    ///
    /// All formulas below were derived by COM measurement: comparing
    /// `Range.Information(wdInformation)` line heights across many
    /// font/size combinations and fitting the formula to measured values.
    ///
    /// Two paths:
    /// 1. **CJK fonts** (MS Gothic, MS Mincho, Yu Gothic, Yu Mincho, Meiryo):
    ///    `lh = (winAscent + winDescent) / UPM × fontSize × 83/64`
    ///    The 83/64 ratio (≈1.296875) was determined by measuring CJK font
    ///    line heights via COM and solving for the multiplier.
    ///    Validated: Yu Gothic 10.5pt → COM reports 351tw (17.55pt).
    ///
    /// 2. **Western fonts**:
    ///    ppem = round(fontSize_pt × 96 / 72)
    ///    height_px = round(winAscent × ppem) + round(winDescent × ppem)
    ///    hhea_excess = max(0, hhea_total - win_total)
    ///    line_height_pt = (height_px + round(hhea_excess × ppem)) × 15/20
    ///    The 15/20 (=0.75) converts GDI pixels (at 96dpi) to points (at 72dpi):
    ///    72/96 = 0.75. This is a standard DPI conversion, not an internal constant.
    ///
    /// The `dpi` parameter is ignored — kept for API compatibility.
    pub fn word_line_height(&self, font_size: f32, _dpi: f32) -> f32 {
        self.word_ascent_pt(font_size) + self.word_descent_pt(font_size)
    }

    /// Ascent component in points (includes external leading).
    /// For mixed-run lines: use max(word_ascent_pt) across all runs.
    pub fn word_ascent_pt(&self, font_size: f32) -> f32 {
        if self.is_cjk_83_64_font() {
            let win_sum = self.win_ascent + self.win_descent;
            let total = win_sum * font_size * (83.0 / 64.0);
            return total * self.win_ascent / (self.win_ascent + self.win_descent);
        }

        let ppem = (font_size * 96.0 / 72.0).round();
        let font_ascent = pixel_round(self.win_ascent, ppem);

        let win_total = self.win_ascent + self.win_descent;
        let hhea_total = self.ascent + self.descent + self.line_gap;
        let hhea_excess = (hhea_total - win_total).max(0.0);
        let extra_leading = pixel_round(hhea_excess, ppem);

        (font_ascent + extra_leading) * 15.0 / 20.0
    }

    /// Descent component in points.
    /// For mixed-run lines: use max(word_descent_pt) across all runs.
    pub fn word_descent_pt(&self, font_size: f32) -> f32 {
        if self.is_cjk_83_64_font() {
            let win_sum = self.win_ascent + self.win_descent;
            let total = win_sum * font_size * (83.0 / 64.0);
            return total * self.win_descent / (self.win_ascent + self.win_descent);
        }

        let ppem = (font_size * 96.0 / 72.0).round();
        let font_descent = pixel_round(self.win_descent, ppem);

        font_descent * 15.0 / 20.0
    }

    /// Standard line height WITHOUT CJK 83/64 multiplier.
    /// Used when adjustLineHeightInTable=true (compat65).
    pub fn word_line_height_standard(&self, font_size: f32) -> f32 {
        let ppem = (font_size * 96.0 / 72.0).round();
        let font_ascent = pixel_round(self.win_ascent, ppem);
        let win_total = self.win_ascent + self.win_descent;
        let hhea_total = self.ascent + self.descent + self.line_gap;
        let hhea_excess = (hhea_total - win_total).max(0.0);
        let extra_leading = pixel_round(hhea_excess, ppem);
        let font_descent = pixel_round(self.win_descent, ppem);
        (font_ascent + extra_leading + font_descent) * 15.0 / 20.0
    }

    /// Line height for table cells: uses floor for descent rounding.
    /// COM measurement confirmed: table cell line height uses floor(winDescent/UPM * ppem)
    /// instead of ceil, resulting in 1px smaller height for some font/size combinations.
    pub fn word_line_height_table_cell(&self, font_size: f32) -> f32 {
        let ppem = (font_size * 96.0 / 72.0).round();
        let font_ascent = pixel_round(self.win_ascent, ppem);
        let font_descent = (self.win_descent * ppem).floor();    // floor for table cells
        let base = (font_ascent + font_descent) * 72.0 / 96.0;
        if self.is_cjk_83_64_font() {
            base * 83.0 / 64.0
        } else {
            base
        }
    }

    /// Returns true if this font uses the CJK line height multiplier 83/64.
    ///
    /// Determined by COM measurement: measuring line heights for each font
    /// and checking which ones match the 83/64 formula vs the Western formula.
    /// Result: CJK font families use 83/64 regardless of lineGap value.
    /// Western fonts (Century, Cambria) do NOT, even with lineGap=0.
    /// Meiryo uses 83/64 despite being a modern font.
    ///
    /// See tools/metrics/verify_exact_cjk.py for the measurement script.
    pub fn is_cjk_83_64_font(&self) -> bool {
        matches!(
            self.family.as_str(),
            "MS Gothic" | "MS PGothic" | "MS Mincho" | "MS PMincho"
                | "Yu Gothic Regular" | "Yu Gothic Bold"
                | "Yu Mincho Regular" | "Yu Mincho Demibold"
                | "Meiryo"
        )
    }
}

/// Registry of font metrics for multiple font families.
/// Backed by real measurements extracted from Windows system fonts.
#[derive(Clone)]
pub struct FontMetricsRegistry {
    fonts: HashMap<String, FontMetrics>,
    default_family: String,
    /// COM-measured line heights: font → size_str → grid_key → height_pt
    com_line_heights: HashMap<String, HashMap<String, HashMap<String, f32>>>,
    /// GDI-measured character widths: font → ppem → codepoint → width_px
    /// These override the formula-based widths where GDI hinting produces different results.
    gdi_widths: HashMap<String, HashMap<u32, HashMap<u32, u32>>>,
    /// GDI-measured tmHeight/tmAscent/tmDescent: font → ppem → (height, ascent, descent) in pixels
    /// ceil(winAscent/upm*ppem) + ceil(winDescent/upm*ppem) ≠ tmHeight due to hinting.
    gdi_heights: HashMap<String, HashMap<u32, (u32, u32, u32)>>,
}

impl FontMetricsRegistry {
    /// Load the embedded font metrics data, cached globally after first call.
    pub fn load() -> Self {
        use std::sync::OnceLock;
        static CACHED: OnceLock<FontMetricsRegistry> = OnceLock::new();
        CACHED.get_or_init(Self::load_inner).clone()
    }

    fn load_inner() -> Self {
        #[cfg(has_local_font_metrics)]
        let raw_json = include_str!("data/font_metrics_compact.json");
        #[cfg(not(has_local_font_metrics))]
        let raw_json = include_str!("data/fallback_metrics.json");
        let raw_list: Vec<RawFontMetrics> =
            serde_json::from_str(raw_json).expect("embedded font metrics should be valid JSON");

        let mut fonts = HashMap::new();

        for raw in raw_list {
            let upm = raw.units_per_em as f32;
            let ascent = raw.ascender as f32 / upm;
            let descent = (-raw.descender) as f32 / upm; // descender is negative in fonts
            let line_gap = raw.line_gap.max(0) as f32 / upm;

            // OS/2 win metrics (fall back to hhea if not present)
            let win_ascent = if raw.win_ascent > 0 {
                raw.win_ascent as f32 / upm
            } else {
                ascent
            };
            let win_descent = if raw.win_descent > 0 {
                raw.win_descent as f32 / upm
            } else {
                descent
            };
            let typo_ascent = if raw.typo_ascender != 0 {
                raw.typo_ascender as f32 / upm
            } else {
                ascent
            };
            let typo_descent = (-raw.typo_descender).max(0) as f32 / upm;
            let typo_line_gap = raw.typo_line_gap.max(0) as f32 / upm;

            let mut char_widths = HashMap::new();
            for (&codepoint, &advance) in &raw.widths {
                if let Some(c) = char::from_u32(codepoint) {
                    char_widths.insert(c, advance as f32 / upm);
                }
            }

            let metrics = FontMetrics {
                family: raw.family.clone(),
                units_per_em: raw.units_per_em,
                ascent,
                descent,
                line_gap,
                win_ascent,
                win_descent,
                typo_ascent,
                typo_descent,
                typo_line_gap,
                char_widths,
            };

            // Store under exact name
            fonts.insert(raw.family.clone(), metrics.clone());

            // Also store under base family name (without "Bold", "Regular", etc.)
            // so lookup by "Calibri" finds "Calibri" even if only "Calibri Bold" was stored
            let base = base_family_name(&raw.family);
            if base != raw.family {
                fonts.entry(base).or_insert(metrics);
            }
        }

        // Load COM-measured line height table
        let com_line_heights: HashMap<String, HashMap<String, HashMap<String, f32>>> = {
            #[cfg(has_local_font_metrics)]
            {
                let lh_json = include_str!("data/com_line_height_table.json");
                serde_json::from_str(lh_json).unwrap_or_default()
            }
            #[cfg(not(has_local_font_metrics))]
            { HashMap::new() }
        };

        // Load GDI-measured character width overrides
        // These correct for GDI hinting that round(advance * ppem / upm) cannot reproduce
        let gdi_widths: HashMap<String, HashMap<u32, HashMap<u32, u32>>> = {
            let gdi_json = include_str!("data/gdi_width_overrides.json");
            // Parse: font_name -> ppem_str -> {codepoint_str: width_px}
            let raw: HashMap<String, HashMap<String, HashMap<String, u32>>> =
                serde_json::from_str(gdi_json).unwrap_or_default();
            // Convert string keys to numeric
            let mut result = HashMap::new();
            for (font, ppem_map) in raw {
                let mut ppem_result = HashMap::new();
                for (ppem_str, char_map) in ppem_map {
                    if let Ok(ppem) = ppem_str.parse::<u32>() {
                        let mut char_result = HashMap::new();
                        for (cp_str, width) in char_map {
                            if let Ok(cp) = cp_str.parse::<u32>() {
                                char_result.insert(cp, width);
                            }
                        }
                        ppem_result.insert(ppem, char_result);
                    }
                }
                result.insert(font, ppem_result);
            }
            result
        };

        // Load GDI-measured tmHeight table
        let gdi_heights: HashMap<String, HashMap<u32, (u32, u32, u32)>> = {
            let ht_json = include_str!("data/gdi_height_table.json");
            let raw: HashMap<String, HashMap<String, serde_json::Value>> =
                serde_json::from_str(ht_json).unwrap_or_default();
            let mut result = HashMap::new();
            for (font, ppem_map) in raw {
                // Convert font name: underscores to spaces for matching
                let font_name = font.replace('_', " ");
                let mut ppem_result = HashMap::new();
                for (ppem_str, val) in ppem_map {
                    if let Ok(ppem) = ppem_str.parse::<u32>() {
                        if let Some(obj) = val.as_object() {
                            let h = obj.get("h").and_then(|v| v.as_u64()).unwrap_or(0) as u32;
                            let a = obj.get("a").and_then(|v| v.as_u64()).unwrap_or(0) as u32;
                            let d = obj.get("d").and_then(|v| v.as_u64()).unwrap_or(0) as u32;
                            ppem_result.insert(ppem, (h, a, d));
                        }
                    }
                }
                result.insert(font_name, ppem_result);
            }
            result
        };

        Self {
            fonts,
            default_family: "Calibri".to_string(),
            com_line_heights,
            gdi_widths,
            gdi_heights,
        }
    }

    /// Look up COM-measured line height for a font, size, and grid pitch.
    /// Returns None if not in the table (falls back to calculation).
    pub fn com_line_height(&self, family: &str, font_size: f32, grid_pitch: Option<f32>) -> Option<f32> {
        let normalized = normalize_family_name(family);
        let font_data = self.com_line_heights.get(family)
            .or_else(|| self.com_line_heights.get(&normalized))?;

        // Find exact or nearest size
        let size_key = format_size_key(font_size);
        let size_data = font_data.get(&size_key)?;

        // Determine grid key
        let grid_key = match grid_pitch {
            None => "no_grid".to_string(),
            Some(pitch) => {
                let pitch_twips = (pitch * 20.0).round() as i32;
                let key = format!("grid{}", pitch_twips);
                if size_data.contains_key(&key) {
                    key
                } else if size_data.contains_key("default_grid") && pitch_twips == 360 {
                    "default_grid".to_string()
                } else {
                    return None; // No matching grid pitch in table
                }
            }
        };

        size_data.get(&grid_key).copied()
    }

    /// Look up COM-measured line height for table cell (grid snap disabled).
    pub fn com_line_height_table_cell(&self, family: &str, font_size: f32) -> Option<f32> {
        let normalized = normalize_family_name(family);
        let font_data = self.com_line_heights.get(family)
            .or_else(|| self.com_line_heights.get(&normalized))?;
        let size_key = format_size_key(font_size);
        let size_data = font_data.get(&size_key)?;
        size_data.get("table_cell").copied()
            .or_else(|| size_data.get("no_grid").copied())
    }

    /// Get metrics for a font family. Falls back to default (Calibri) if not found.
    pub fn get(&self, family: &str) -> &FontMetrics {
        // Try exact match first
        if let Some(m) = self.fonts.get(family) {
            return m;
        }
        // Try normalized name
        let normalized = normalize_family_name(family);
        if let Some(m) = self.fonts.get(&normalized) {
            return m;
        }
        // Try base name
        let base = base_family_name(family);
        if let Some(m) = self.fonts.get(&base) {
            return m;
        }
        // Fallback to default
        self.fonts.get(&self.default_family).unwrap_or_else(|| {
            self.fonts.values().next().expect("FontMetricsRegistry has no fonts loaded")
        })
    }

    /// Get the default font metrics (Calibri).
    pub fn default_metrics(&self) -> &FontMetrics {
        self.get(&self.default_family)
    }

    /// Get GDI-measured tmHeight for a font at a given ppem.
    /// Returns (height_px, ascent_px, descent_px) or None if not in table.
    pub fn gdi_height(&self, family: &str, ppem: u32) -> Option<(u32, u32, u32)> {
        let normalized = normalize_family_name(family);
        self.gdi_heights.get(family)
            .or_else(|| self.gdi_heights.get(&normalized))
            .and_then(|ppem_map| ppem_map.get(&ppem).copied())
    }

    /// Character width with GDI font fallback and hinting overrides.
    /// When a CJK character is rendered with a Latin font (e.g. Calibri),
    /// GDI substitutes MS UI Gothic. This method mimics that behavior.
    /// For Latin fonts, GDI hinting overrides are applied when available.
    pub fn char_width_pt_with_fallback(&self, c: char, font_size: f32, metrics: &FontMetrics) -> f32 {
        // UPM=256 CJK monospace fonts: fullwidth/halfwidth use fontSize directly
        if metrics.units_per_em == 256 {
            if is_fullwidth(c) { return font_size; }
            let advance_em = metrics.char_width_em(c);
            if is_halfwidth_katakana(c) || advance_em <= 0.51 { return font_size / 2.0; }
        }

        // GDI hinting override: use pre-measured width if available
        let ppem = (font_size * 96.0 / 72.0) as u32;
        if let Some(font_ppems) = self.gdi_widths.get(&metrics.family) {
            if let Some(char_widths) = font_ppems.get(&ppem) {
                if let Some(&width_px) = char_widths.get(&(c as u32)) {
                    return width_px as f32 * 72.0 / 96.0;
                }
            }
        }

        // If the font has this character's width measured, use it directly
        if metrics.char_widths.contains_key(&c) {
            return metrics.char_width_pt(c, font_size);
        }

        // CJK character + Latin font → GDI fallback to MS UI Gothic
        if is_cjk_or_symbol(c) && !is_cjk_font_family(&metrics.family) {
            if let Some(fallback) = self.fonts.get("MS UI Gothic")
                .or_else(|| self.fonts.get("MS Gothic"))
            {
                return fallback.char_width_pt(c, font_size);
            }
        }

        // Default: use the font's own heuristic
        metrics.char_width_pt(c, font_size)
    }

    /// Pre-resolve the GDI character width map for a given font family and font size.
    /// Returns the ppem-specific width map (codepoint → width_px), avoiding
    /// repeated HashMap lookups in per-character loops.
    pub fn get_gdi_char_widths(&self, family: &str, font_size: f32) -> Option<&HashMap<u32, u32>> {
        let ppem = (font_size * 96.0 / 72.0) as u32;
        self.gdi_widths.get(family)?.get(&ppem)
    }

    /// Character width using a pre-resolved GDI width map.
    /// This avoids the 2-level HashMap lookup per character that
    /// `char_width_pt_with_fallback` performs.
    pub fn char_width_pt_with_gdi_map(
        &self,
        c: char,
        font_size: f32,
        metrics: &FontMetrics,
        gdi_map: Option<&HashMap<u32, u32>>,
    ) -> f32 {
        // UPM=256 CJK monospace fonts: fullwidth/halfwidth use fontSize directly,
        // NOT GDI table (GDI returns ceil_even which is wrong for Word layout).
        if metrics.units_per_em == 256 {
            if is_fullwidth(c) {
                return font_size;
            }
            let advance_em = metrics.char_width_em(c);
            if is_halfwidth_katakana(c) || advance_em <= 0.51 {
                return font_size / 2.0;
            }
        }

        // GDI hinting override via pre-resolved map (for proportional chars)
        if let Some(char_widths) = gdi_map {
            if let Some(&width_px) = char_widths.get(&(c as u32)) {
                return width_px as f32 * 72.0 / 96.0;
            }
        }

        // If the font has this character's width measured, use it directly
        if metrics.char_widths.contains_key(&c) {
            return metrics.char_width_pt(c, font_size);
        }

        // CJK character + Latin font → GDI fallback to MS UI Gothic
        if is_cjk_or_symbol(c) && !is_cjk_font_family(&metrics.family) {
            if let Some(fallback) = self.fonts.get("MS UI Gothic")
                .or_else(|| self.fonts.get("MS Gothic"))
            {
                return fallback.char_width_pt(c, font_size);
            }
        }

        // Default: use the font's own heuristic
        metrics.char_width_pt(c, font_size)
    }
}

/// Check if a character is CJK or a symbol that GDI renders with an East Asian font.
fn is_cjk_or_symbol(c: char) -> bool {
    let cp = c as u32;
    matches!(cp,
        0x2E80..=0x9FFF |    // CJK radicals, kangxi, CJK unified ideographs
        0x3000..=0x303F |    // CJK symbols and punctuation
        0x3040..=0x309F |    // Hiragana
        0x30A0..=0x30FF |    // Katakana
        0x31F0..=0x31FF |    // Katakana phonetic extensions
        0x3200..=0x33FF |    // Enclosed CJK, CJK compatibility
        0xF900..=0xFAFF |    // CJK compatibility ideographs
        0xFE30..=0xFE4F |    // CJK compatibility forms
        0xFF00..=0xFFEF |    // Halfwidth and fullwidth forms
        0x20000..=0x2A6DF |  // CJK unified ideographs extension B
        0x2190..=0x21FF |    // Arrows
        0x2200..=0x22FF |    // Mathematical operators
        0x2500..=0x257F |    // Box drawing
        0x2580..=0x259F |    // Block elements
        0x25A0..=0x25FF |    // Geometric shapes
        0x2600..=0x26FF |    // Miscellaneous symbols
        0x2700..=0x27BF |    // Dingbats
        0x2010..=0x2044      // General punctuation subset
    )
}

/// Check if a font family is a CJK font (has native CJK glyphs).
fn is_cjk_font_family(family: &str) -> bool {
    matches!(family,
        "MS Gothic" | "MS Mincho" | "MS PGothic" | "MS PMincho" |
        "MS UI Gothic" | "Yu Gothic" | "Yu Mincho" | "Meiryo" |
        "Noto Sans JP" | "Noto Serif JP" | "Noto Sans CJK JP" | "Noto Serif CJK JP" |
        "HGPGothicE" | "HGPMinchoE" | "HGGothicE" | "HGMinchoE" |
        "HGSGothicE" | "HGSMinchoE" | "HGPGothicM" | "HGPMinchoB" |
        "HGPSoeiKakugothicUB" | "HGSoeiKakugothicUB" |
        "HGMaruGothicMPRO" | "HGSMaruGothicMPRO"
    )
}

/// Strip weight/style suffixes to get the base family name.
fn base_family_name(name: &str) -> String {
    let suffixes = [
        " Bold", " Regular", " Demibold", " Light", " Medium",
        " Italic", " Oblique", " Thin", " Black", " Heavy",
    ];
    let mut result = name.to_string();
    for suffix in &suffixes {
        if let Some(stripped) = result.strip_suffix(suffix) {
            result = stripped.to_string();
        }
    }
    result
}

/// Format font size as JSON key (e.g. 10.5 → "10.5", 12.0 → "12.0")
fn format_size_key(size: f32) -> String {
    if size.fract() == 0.0 {
        format!("{:.0}", size)  // "12" not "12.0"
    } else {
        format!("{}", size)     // "10.5"
    }
}

/// Normalize common font family name aliases used in OOXML.
fn normalize_family_name(name: &str) -> String {
    match name {
        "ＭＳ ゴシック" | "MS ゴシック" | "ＭＳ Gothic" => "MS Gothic".to_string(),
        "ＭＳ Ｐゴシック" | "MS Ｐゴシック" | "ＭＳ PGothic" => "MS PGothic".to_string(),
        "ＭＳ 明朝" | "MS 明朝" | "ＭＳ Mincho" => "MS Mincho".to_string(),
        "ＭＳ Ｐ明朝" | "MS Ｐ明朝" | "ＭＳ PMincho" => "MS PMincho".to_string(),
        "游ゴシック" | "Yu Gothic UI" => "Yu Gothic Regular".to_string(),
        "游ゴシック Medium" => "Yu Gothic Regular".to_string(),
        "游明朝" => "Yu Mincho Regular".to_string(),
        "游明朝 Demibold" => "Yu Mincho Demibold".to_string(),
        "メイリオ" | "Meiryo UI" => "Meiryo".to_string(),
        // Arial Unicode MS is not always installed; fall back to Arial
        "Arial Unicode MS" => "Arial".to_string(),
        // OSS metric-compatible fonts
        "Carlito" => "Carlito".to_string(),
        "Caladea" => "Caladea".to_string(),
        "Liberation Sans" => "Liberation Sans".to_string(),
        "Liberation Serif" => "Liberation Serif".to_string(),
        "Noto Sans JP" | "Noto Sans CJK JP" => "Noto Sans JP".to_string(),
        "Noto Serif JP" | "Noto Serif CJK JP" => "Noto Serif JP".to_string(),
        _ => name.to_string(),
    }
}

/// Half-width katakana: U+FF65..U+FF9F (ｦ, ｧ, ｨ, ... ﾝ, ﾞ, ﾟ)
fn is_halfwidth_katakana(ch: char) -> bool {
    matches!(ch as u32, 0xFF65..=0xFF9F)
}

fn is_fullwidth(ch: char) -> bool {
    matches!(ch as u32,
        0x2500..=0x257F |  // Box Drawing
        0x2580..=0x259F |  // Block Elements
        0x25A0..=0x25FF |  // Geometric Shapes (□, ◎, ○, ● etc.)
        0x2600..=0x26FF |  // Miscellaneous Symbols
        0x2700..=0x27BF |  // Dingbats
        0x3000..=0x303F |  // CJK Symbols and Punctuation
        0x3040..=0x309F |  // Hiragana
        0x30A0..=0x30FF |  // Katakana (full-width)
        0x3400..=0x4DBF |  // CJK Unified Ideographs Extension A
        0x4E00..=0x9FFF |  // CJK Unified Ideographs
        0xF900..=0xFAFF |  // CJK Compatibility Ideographs
        0xFF01..=0xFF60 |  // Fullwidth Latin / symbols
        0xFFE0..=0xFFE6 |  // Fullwidth currency/symbols
        0x20000..=0x2A6DF  // CJK Unified Ideographs Extension B
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_loads() {
        let reg = FontMetricsRegistry::load();
        let calibri = reg.get("Calibri");
        assert_eq!(calibri.family, "Calibri");
        // Calibri space should be ~0.226em (463/2048)
        let space_w = calibri.char_width_em(' ');
        assert!(space_w > 0.2 && space_w < 0.3, "space width: {}", space_w);
    }

    #[test]
    fn test_japanese_font_lookup() {
        let reg = FontMetricsRegistry::load();
        let yu = reg.get("Yu Gothic Regular");
        assert!(yu.family.contains("Yu Gothic"));
        // CJK char should be ~1.0em
        let kanji_w = yu.char_width_em('漢');
        assert!(kanji_w > 0.9 && kanji_w < 1.1, "kanji width: {}", kanji_w);
    }

    #[test]
    fn test_family_alias() {
        let reg = FontMetricsRegistry::load();
        let ms = reg.get("ＭＳ ゴシック");
        assert!(ms.family.contains("MS Gothic") || ms.family.contains("Calibri"));
    }

    #[test]
    fn test_fallback_to_default() {
        let reg = FontMetricsRegistry::load();
        let unknown = reg.get("NonexistentFont");
        assert_eq!(unknown.family, "Calibri");
    }

    #[test]
    fn test_word_line_height_vs_word_com() {
        // Word COM measured line gaps (single spacing, no grid).
        // Formula: max(word(run_font, size, 150), word(default_font, size, 150))
        // Expected: avg error < 0.5pt, all within 1.0pt.
        let reg = FontMetricsRegistry::load();
        let default_metrics = reg.default_metrics();
        const DPI: f32 = 150.0;

        // (font_family, font_size, word_com_gap)
        // CJK fonts use: (winAsc+winDes)/UPM × fontSize × 83/64
        // Western fonts use: font metrics formula
        let test_cases: Vec<(&str, f32, f32)> = vec![
            ("Calibri", 10.5, 13.45),
            ("Calibri", 11.0, 14.00),
            ("Calibri", 12.0, 15.55),
            ("Calibri", 14.0, 17.70),
            ("Arial", 10.5, 13.45),
            ("Arial", 14.0, 17.70),
            ("Times New Roman", 12.0, 15.55),
            // MS Gothic: winSum=1.0, 1.0 × fs × 83/64 = fs × 1.296875
            ("MS Gothic", 10.5, 13.62),
            ("MS Gothic", 14.0, 18.16),
            // MS Mincho: winSum=1.0, same formula
            ("MS Mincho", 10.5, 13.62),
            ("MS Mincho", 12.0, 15.56),
            ("MS Mincho", 24.0, 31.13),
            // Yu Gothic: winSum=1.287, 1.287 × fs × 83/64
            // 10.5: 1.287 × 10.5 × 1.296875 = 17.53 (COM: 351tw = 17.55pt)
            ("Yu Gothic Regular", 10.5, 17.55),
            ("Yu Gothic Regular", 11.0, 18.40),
            ("Yu Gothic Regular", 12.0, 20.05),
            ("Yu Gothic Regular", 14.0, 23.55),
        ];

        let mut total_err = 0.0_f32;
        let mut max_err = 0.0_f32;

        for (family, size, com_gap) in &test_cases {
            let m = reg.get(family);
            let run_h = m.word_line_height(*size, DPI);
            let def_h = default_metrics.word_line_height(*size, DPI);
            let predicted = run_h.max(def_h);
            let err = (predicted - com_gap).abs();
            total_err += err;
            max_err = max_err.max(err);
            assert!(
                err < 1.5,
                "{} {}pt: predicted={:.2}, COM={:.2}, err={:.2}",
                family, size, predicted, com_gap, err
            );
        }

        let avg_err = total_err / test_cases.len() as f32;
        assert!(avg_err < 0.5, "avg error {:.3}pt exceeds 0.5pt", avg_err);
    }
}

/// GDI hinting width overrides for UPM=256 fonts (MS Mincho/Gothic) at ppem=14.
/// At ppem=14, GDI applies hinting that changes hiragana/katakana glyph widths
/// from the nominal 14px to smaller values. This causes text wrapping differences.
/// Measured via GetTextExtentPoint32W on Windows with MS Mincho/Gothic at -14px.
fn gdi_kana_width_px_ppem14(c: char) -> Option<f32> {
    match c {
        'ぁ' => Some(10.0), 'あ' => Some(13.0), 'ぃ' => Some(11.0), 'い' => Some(13.0),
        'ぅ' => Some(8.0),  'う' => Some(10.0), 'ぇ' => Some(11.0), 'え' => Some(13.0),
        'ぉ' => Some(11.0), 'お' => Some(13.0), 'き' => Some(12.0), 'ぎ' => Some(13.0),
        'く' => Some(8.0),  'ぐ' => Some(11.0), 'け' => Some(13.0), 'こ' => Some(11.0),
        'ご' => Some(13.0), 'さ' => Some(11.0), 'ざ' => Some(12.0), 'し' => Some(11.0),
        'じ' => Some(11.0), 'す' => Some(13.0), 'そ' => Some(13.0), 'ぞ' => Some(13.0),
        'た' => Some(13.0), 'だ' => Some(13.0), 'ち' => Some(12.0), 'ぢ' => Some(13.0),
        'っ' => Some(11.0), 'つ' => Some(13.0), 'づ' => Some(13.0), 'て' => Some(13.0),
        'で' => Some(13.0), 'と' => Some(11.0), 'ど' => Some(12.0), 'な' => Some(13.0),
        'に' => Some(13.0), 'ひ' => Some(13.0), 'び' => Some(13.0), 'ぴ' => Some(13.0),
        'ま' => Some(12.0), 'も' => Some(11.0), 'ゃ' => Some(12.0), 'ゅ' => Some(12.0),
        'ょ' => Some(10.0), 'よ' => Some(12.0), 'ら' => Some(11.0), 'り' => Some(10.0),
        'る' => Some(12.0), 'ろ' => Some(12.0), 'ゎ' => Some(12.0), 'を' => Some(12.0),
        'ん' => Some(13.0), 'ゔ' => Some(12.0), 'ゝ' => Some(10.0), 'ゞ' => Some(10.0),
        'ァ' => Some(11.0), 'ア' => Some(13.0), 'ィ' => Some(9.0),  'イ' => Some(12.0),
        'ゥ' => Some(11.0), 'ウ' => Some(13.0), 'ェ' => Some(10.0), 'エ' => Some(13.0),
        'ォ' => Some(11.0), 'オ' => Some(13.0), 'カ' => Some(12.0), 'ガ' => Some(13.0),
        'キ' => Some(13.0), 'ク' => Some(11.0), 'グ' => Some(13.0), 'ケ' => Some(13.0),
        'ゲ' => Some(13.0), 'コ' => Some(11.0), 'ゴ' => Some(12.0), 'シ' => Some(13.0),
        'ジ' => Some(13.0), 'ス' => Some(13.0), 'セ' => Some(13.0), 'ソ' => Some(11.0),
        'ゾ' => Some(12.0), 'タ' => Some(11.0), 'ダ' => Some(13.0), 'チ' => Some(13.0),
        'ヂ' => Some(13.0), 'ッ' => Some(10.0), 'ツ' => Some(12.0), 'ヅ' => Some(13.0),
        'テ' => Some(12.0), 'デ' => Some(13.0), 'ト' => Some(9.0),  'ド' => Some(10.0),
        'ナ' => Some(13.0), 'ニ' => Some(13.0), 'ヌ' => Some(12.0), 'ネ' => Some(13.0),
        'ノ' => Some(10.0), 'ヒ' => Some(11.0), 'ビ' => Some(12.0), 'ピ' => Some(12.0),
        'フ' => Some(11.0), 'ブ' => Some(12.0), 'プ' => Some(12.0), 'ヘ' => Some(13.0),
        'ベ' => Some(13.0), 'ペ' => Some(13.0), 'ホ' => Some(13.0), 'ボ' => Some(13.0),
        'ポ' => Some(13.0), 'マ' => Some(13.0), 'ミ' => Some(9.0),  'メ' => Some(10.0),
        'モ' => Some(13.0), 'ャ' => Some(11.0), 'ュ' => Some(11.0), 'ユ' => Some(13.0),
        'ョ' => Some(9.0),  'ヨ' => Some(10.0), 'ラ' => Some(11.0), 'リ' => Some(10.0),
        'レ' => Some(12.0), 'ロ' => Some(12.0), 'ヮ' => Some(11.0), 'ワ' => Some(13.0),
        'ヲ' => Some(11.0), 'ン' => Some(12.0), 'ヴ' => Some(13.0), 'ヵ' => Some(10.0),
        'ヶ' => Some(11.0), 'ヷ' => Some(13.0), 'ヸ' => Some(13.0), 'ヺ' => Some(13.0),
        '・' => Some(7.0),  'ー' => Some(13.0), 'ヽ' => Some(10.0), 'ヾ' => Some(10.0),
        '゛' | '゜' => Some(7.0),
        _ => None,
    }
}
