use serde::{Deserialize, Serialize};
use std::collections::HashMap;

fn default_upm() -> u16 { 2048 }

/// Pixel-rounded multiplication matching Word's font metrics.
/// All font metric values are pre-normalized to [0,1] range (÷UPM),
/// so this is simply `round(value * ppem)`.
fn pixel_round(value_normalized: f32, ppem: f32) -> f32 {
    (value_normalized * ppem).round()
}

/// Raw metrics data as generated by tools/font-metrics-gen.
/// Widths are keyed by codepoint (u32) and stored in font units.
#[derive(Debug, Clone, Deserialize)]
struct RawFontMetrics {
    family: String,
    units_per_em: u16,
    ascender: i16,
    descender: i16,
    line_gap: i16,
    #[serde(default)]
    win_ascent: u16,
    #[serde(default)]
    win_descent: u16,
    #[serde(default)]
    typo_ascender: i16,
    #[serde(default)]
    typo_descender: i16,
    #[serde(default)]
    typo_line_gap: i16,
    widths: HashMap<u32, u16>,
}

/// Per-character font metrics normalized to 1em.
/// All widths are expressed as a fraction of the em-square.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FontMetrics {
    pub family: String,
    /// Units per em (e.g. 256 for MS Gothic/Mincho, 2048 for most others)
    #[serde(default = "default_upm")]
    pub units_per_em: u16,
    /// hhea ascent normalized to 1em
    pub ascent: f32,
    /// hhea descent normalized to 1em (positive value)
    pub descent: f32,
    /// hhea line gap normalized to 1em
    pub line_gap: f32,
    /// OS/2 usWinAscent normalized to 1em
    pub win_ascent: f32,
    /// OS/2 usWinDescent normalized to 1em (positive value)
    pub win_descent: f32,
    /// OS/2 sTypoAscender normalized to 1em
    pub typo_ascent: f32,
    /// OS/2 |sTypoDescender| normalized to 1em (positive value)
    pub typo_descent: f32,
    /// OS/2 sTypoLineGap normalized to 1em
    pub typo_line_gap: f32,
    /// Per-character advance widths, normalized to 1em.
    pub char_widths: HashMap<char, f32>,
}

impl FontMetrics {
    /// Look up the advance width for a character (normalized to 1em).
    /// Falls back to fullwidth/halfwidth heuristics for unmeasured chars.
    pub fn char_width_em(&self, c: char) -> f32 {
        self.char_widths.get(&c).copied().unwrap_or_else(|| {
            if is_halfwidth_katakana(c) {
                0.5
            } else if is_fullwidth(c) {
                1.0
            } else {
                0.5
            }
        })
    }

    /// Character width in points at a given font size.
    ///
    /// Word uses GDI pixel-grid snapping for character placement:
    ///   ppem = round(fontSize_pt * 96 / 72)
    ///   char_width_px = round(advance_em * ppem)
    ///   char_width_pt = char_width_px * 72 / 96
    ///
    /// COM measurement confirmed: this produces correct widths for all fonts
    /// including monospace CJK (MS Gothic/Mincho UPM=256).
    pub fn char_width_pt(&self, c: char, font_size: f32) -> f32 {
        let advance_em = self.char_width_em(c);
        let ppem = (font_size * 96.0 / 72.0).round();
        (advance_em * ppem).round() * 72.0 / 96.0
    }

    /// Simple line height in points (no pixel rounding).
    /// Uses max(win, hhea) metrics normalized to 1em.
    pub fn line_height_pt(&self, font_size: f32) -> f32 {
        self.line_height_ratio() * font_size
    }

    /// The font's line height as a ratio of 1em.
    /// max(win, hhea) metrics — the raw font line height before any
    /// paragraph-level minimums or spacing multipliers.
    pub fn line_height_ratio(&self) -> f32 {
        let win_height = self.win_ascent + self.win_descent;
        let hhea_height = self.ascent + self.descent + self.line_gap;
        win_height.max(hhea_height)
    }

    /// Line height calculation matching Word's behavior.
    ///
    /// All formulas below were derived by COM measurement: comparing
    /// `Range.Information(wdInformation)` line heights across many
    /// font/size combinations and fitting the formula to measured values.
    ///
    /// Two paths:
    /// 1. **CJK fonts** (MS Gothic, MS Mincho, Yu Gothic, Yu Mincho, Meiryo):
    ///    `lh = (winAscent + winDescent) / UPM × fontSize × 83/64`
    ///    The 83/64 ratio (≈1.296875) was determined by measuring CJK font
    ///    line heights via COM and solving for the multiplier.
    ///    Validated: Yu Gothic 10.5pt → COM reports 351tw (17.55pt).
    ///
    /// 2. **Western fonts**:
    ///    ppem = round(fontSize_pt × 96 / 72)
    ///    height_px = round(winAscent × ppem) + round(winDescent × ppem)
    ///    hhea_excess = max(0, hhea_total - win_total)
    ///    line_height_pt = (height_px + round(hhea_excess × ppem)) × 15/20
    ///    The 15/20 (=0.75) converts GDI pixels (at 96dpi) to points (at 72dpi):
    ///    72/96 = 0.75. This is a standard DPI conversion, not an internal constant.
    ///
    /// The `dpi` parameter is ignored — kept for API compatibility.
    pub fn word_line_height(&self, font_size: f32, _dpi: f32) -> f32 {
        self.word_ascent_pt(font_size) + self.word_descent_pt(font_size)
    }

    /// Ascent component in points (includes external leading).
    /// For mixed-run lines: use max(word_ascent_pt) across all runs.
    pub fn word_ascent_pt(&self, font_size: f32) -> f32 {
        if self.is_cjk_83_64_font() {
            let win_sum = self.win_ascent + self.win_descent;
            let total = win_sum * font_size * (83.0 / 64.0);
            return total * self.win_ascent / (self.win_ascent + self.win_descent);
        }

        let ppem = (font_size * 96.0 / 72.0).round();
        let font_ascent = pixel_round(self.win_ascent, ppem);

        let win_total = self.win_ascent + self.win_descent;
        let hhea_total = self.ascent + self.descent + self.line_gap;
        let hhea_excess = (hhea_total - win_total).max(0.0);
        let extra_leading = pixel_round(hhea_excess, ppem);

        (font_ascent + extra_leading) * 15.0 / 20.0
    }

    /// Descent component in points.
    /// For mixed-run lines: use max(word_descent_pt) across all runs.
    pub fn word_descent_pt(&self, font_size: f32) -> f32 {
        if self.is_cjk_83_64_font() {
            let win_sum = self.win_ascent + self.win_descent;
            let total = win_sum * font_size * (83.0 / 64.0);
            return total * self.win_descent / (self.win_ascent + self.win_descent);
        }

        let ppem = (font_size * 96.0 / 72.0).round();
        let font_descent = pixel_round(self.win_descent, ppem);

        font_descent * 15.0 / 20.0
    }

    /// Standard line height WITHOUT CJK 83/64 multiplier.
    /// Used when adjustLineHeightInTable=true (compat65).
    pub fn word_line_height_standard(&self, font_size: f32) -> f32 {
        let ppem = (font_size * 96.0 / 72.0).round();
        let font_ascent = pixel_round(self.win_ascent, ppem);
        let win_total = self.win_ascent + self.win_descent;
        let hhea_total = self.ascent + self.descent + self.line_gap;
        let hhea_excess = (hhea_total - win_total).max(0.0);
        let extra_leading = pixel_round(hhea_excess, ppem);
        let font_descent = pixel_round(self.win_descent, ppem);
        (font_ascent + extra_leading + font_descent) * 15.0 / 20.0
    }

    /// Returns true if this font uses the CJK line height multiplier 83/64.
    ///
    /// Determined by COM measurement: measuring line heights for each font
    /// and checking which ones match the 83/64 formula vs the Western formula.
    /// Result: CJK font families use 83/64 regardless of lineGap value.
    /// Western fonts (Century, Cambria) do NOT, even with lineGap=0.
    /// Meiryo uses 83/64 despite being a modern font.
    ///
    /// See tools/metrics/verify_exact_cjk.py for the measurement script.
    fn is_cjk_83_64_font(&self) -> bool {
        matches!(
            self.family.as_str(),
            "MS Gothic" | "MS PGothic" | "MS Mincho" | "MS PMincho"
                | "Yu Gothic Regular" | "Yu Gothic Bold"
                | "Yu Mincho Regular" | "Yu Mincho Demibold"
                | "Meiryo"
        )
    }
}

/// Registry of font metrics for multiple font families.
/// Backed by real measurements extracted from Windows system fonts.
pub struct FontMetricsRegistry {
    fonts: HashMap<String, FontMetrics>,
    default_family: String,
}

impl FontMetricsRegistry {
    /// Load the embedded font metrics data.
    /// If the user has generated metrics from their local fonts (via tools/font-metrics-gen),
    /// those are used. Otherwise, falls back to basic metrics for common fonts.
    pub fn load() -> Self {
        #[cfg(has_local_font_metrics)]
        let raw_json = include_str!("data/font_metrics_compact.json");
        #[cfg(not(has_local_font_metrics))]
        let raw_json = include_str!("data/fallback_metrics.json");
        let raw_list: Vec<RawFontMetrics> =
            serde_json::from_str(raw_json).expect("embedded font metrics should be valid JSON");

        let mut fonts = HashMap::new();

        for raw in raw_list {
            let upm = raw.units_per_em as f32;
            let ascent = raw.ascender as f32 / upm;
            let descent = (-raw.descender) as f32 / upm; // descender is negative in fonts
            let line_gap = raw.line_gap.max(0) as f32 / upm;

            // OS/2 win metrics (fall back to hhea if not present)
            let win_ascent = if raw.win_ascent > 0 {
                raw.win_ascent as f32 / upm
            } else {
                ascent
            };
            let win_descent = if raw.win_descent > 0 {
                raw.win_descent as f32 / upm
            } else {
                descent
            };
            let typo_ascent = if raw.typo_ascender != 0 {
                raw.typo_ascender as f32 / upm
            } else {
                ascent
            };
            let typo_descent = (-raw.typo_descender).max(0) as f32 / upm;
            let typo_line_gap = raw.typo_line_gap.max(0) as f32 / upm;

            let mut char_widths = HashMap::new();
            for (&codepoint, &advance) in &raw.widths {
                if let Some(c) = char::from_u32(codepoint) {
                    char_widths.insert(c, advance as f32 / upm);
                }
            }

            let metrics = FontMetrics {
                family: raw.family.clone(),
                units_per_em: raw.units_per_em,
                ascent,
                descent,
                line_gap,
                win_ascent,
                win_descent,
                typo_ascent,
                typo_descent,
                typo_line_gap,
                char_widths,
            };

            // Store under exact name
            fonts.insert(raw.family.clone(), metrics.clone());

            // Also store under base family name (without "Bold", "Regular", etc.)
            // so lookup by "Calibri" finds "Calibri" even if only "Calibri Bold" was stored
            let base = base_family_name(&raw.family);
            if base != raw.family {
                fonts.entry(base).or_insert(metrics);
            }
        }

        Self {
            fonts,
            default_family: "Calibri".to_string(),
        }
    }

    /// Get metrics for a font family. Falls back to default (Calibri) if not found.
    pub fn get(&self, family: &str) -> &FontMetrics {
        // Try exact match first
        if let Some(m) = self.fonts.get(family) {
            return m;
        }
        // Try normalized name
        let normalized = normalize_family_name(family);
        if let Some(m) = self.fonts.get(&normalized) {
            return m;
        }
        // Try base name
        let base = base_family_name(family);
        if let Some(m) = self.fonts.get(&base) {
            return m;
        }
        // Fallback to default
        self.fonts.get(&self.default_family).unwrap_or_else(|| {
            self.fonts.values().next().expect("FontMetricsRegistry has no fonts loaded")
        })
    }

    /// Get the default font metrics (Calibri).
    pub fn default_metrics(&self) -> &FontMetrics {
        self.get(&self.default_family)
    }
}

/// Strip weight/style suffixes to get the base family name.
fn base_family_name(name: &str) -> String {
    let suffixes = [
        " Bold", " Regular", " Demibold", " Light", " Medium",
        " Italic", " Oblique", " Thin", " Black", " Heavy",
    ];
    let mut result = name.to_string();
    for suffix in &suffixes {
        if let Some(stripped) = result.strip_suffix(suffix) {
            result = stripped.to_string();
        }
    }
    result
}

/// Normalize common font family name aliases used in OOXML.
fn normalize_family_name(name: &str) -> String {
    match name {
        "ＭＳ ゴシック" | "MS ゴシック" | "ＭＳ Gothic" => "MS Gothic".to_string(),
        "ＭＳ Ｐゴシック" | "MS Ｐゴシック" | "ＭＳ PGothic" => "MS PGothic".to_string(),
        "ＭＳ 明朝" | "MS 明朝" | "ＭＳ Mincho" => "MS Mincho".to_string(),
        "ＭＳ Ｐ明朝" | "MS Ｐ明朝" | "ＭＳ PMincho" => "MS PMincho".to_string(),
        "游ゴシック" | "Yu Gothic UI" => "Yu Gothic Regular".to_string(),
        "游ゴシック Medium" => "Yu Gothic Regular".to_string(),
        "游明朝" => "Yu Mincho Regular".to_string(),
        "游明朝 Demibold" => "Yu Mincho Demibold".to_string(),
        _ => name.to_string(),
    }
}

/// Half-width katakana: U+FF65..U+FF9F (ｦ, ｧ, ｨ, ... ﾝ, ﾞ, ﾟ)
fn is_halfwidth_katakana(ch: char) -> bool {
    matches!(ch as u32, 0xFF65..=0xFF9F)
}

fn is_fullwidth(ch: char) -> bool {
    matches!(ch as u32,
        0x2500..=0x257F |  // Box Drawing
        0x2580..=0x259F |  // Block Elements
        0x25A0..=0x25FF |  // Geometric Shapes (□, ◎, ○, ● etc.)
        0x2600..=0x26FF |  // Miscellaneous Symbols
        0x2700..=0x27BF |  // Dingbats
        0x3000..=0x303F |  // CJK Symbols and Punctuation
        0x3040..=0x309F |  // Hiragana
        0x30A0..=0x30FF |  // Katakana (full-width)
        0x3400..=0x4DBF |  // CJK Unified Ideographs Extension A
        0x4E00..=0x9FFF |  // CJK Unified Ideographs
        0xF900..=0xFAFF |  // CJK Compatibility Ideographs
        0xFF01..=0xFF60 |  // Fullwidth Latin / symbols
        0xFFE0..=0xFFE6 |  // Fullwidth currency/symbols
        0x20000..=0x2A6DF  // CJK Unified Ideographs Extension B
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_loads() {
        let reg = FontMetricsRegistry::load();
        let calibri = reg.get("Calibri");
        assert_eq!(calibri.family, "Calibri");
        // Calibri space should be ~0.226em (463/2048)
        let space_w = calibri.char_width_em(' ');
        assert!(space_w > 0.2 && space_w < 0.3, "space width: {}", space_w);
    }

    #[test]
    fn test_japanese_font_lookup() {
        let reg = FontMetricsRegistry::load();
        let yu = reg.get("Yu Gothic Regular");
        assert!(yu.family.contains("Yu Gothic"));
        // CJK char should be ~1.0em
        let kanji_w = yu.char_width_em('漢');
        assert!(kanji_w > 0.9 && kanji_w < 1.1, "kanji width: {}", kanji_w);
    }

    #[test]
    fn test_family_alias() {
        let reg = FontMetricsRegistry::load();
        let ms = reg.get("ＭＳ ゴシック");
        assert!(ms.family.contains("MS Gothic") || ms.family.contains("Calibri"));
    }

    #[test]
    fn test_fallback_to_default() {
        let reg = FontMetricsRegistry::load();
        let unknown = reg.get("NonexistentFont");
        assert_eq!(unknown.family, "Calibri");
    }

    #[test]
    fn test_word_line_height_vs_word_com() {
        // Word COM measured line gaps (single spacing, no grid).
        // Formula: max(word(run_font, size, 150), word(default_font, size, 150))
        // Expected: avg error < 0.5pt, all within 1.0pt.
        let reg = FontMetricsRegistry::load();
        let default_metrics = reg.default_metrics();
        const DPI: f32 = 150.0;

        // (font_family, font_size, word_com_gap)
        // CJK fonts use: (winAsc+winDes)/UPM × fontSize × 83/64
        // Western fonts use: font metrics formula
        let test_cases: Vec<(&str, f32, f32)> = vec![
            ("Calibri", 10.5, 13.45),
            ("Calibri", 11.0, 14.00),
            ("Calibri", 12.0, 15.55),
            ("Calibri", 14.0, 17.70),
            ("Arial", 10.5, 13.45),
            ("Arial", 14.0, 17.70),
            ("Times New Roman", 12.0, 15.55),
            // MS Gothic: winSum=1.0, 1.0 × fs × 83/64 = fs × 1.296875
            ("MS Gothic", 10.5, 13.62),
            ("MS Gothic", 14.0, 18.16),
            // MS Mincho: winSum=1.0, same formula
            ("MS Mincho", 10.5, 13.62),
            ("MS Mincho", 12.0, 15.56),
            ("MS Mincho", 24.0, 31.13),
            // Yu Gothic: winSum=1.287, 1.287 × fs × 83/64
            // 10.5: 1.287 × 10.5 × 1.296875 = 17.53 (COM: 351tw = 17.55pt)
            ("Yu Gothic Regular", 10.5, 17.55),
            ("Yu Gothic Regular", 11.0, 18.40),
            ("Yu Gothic Regular", 12.0, 20.05),
            ("Yu Gothic Regular", 14.0, 23.55),
        ];

        let mut total_err = 0.0_f32;
        let mut max_err = 0.0_f32;

        for (family, size, com_gap) in &test_cases {
            let m = reg.get(family);
            let run_h = m.word_line_height(*size, DPI);
            let def_h = default_metrics.word_line_height(*size, DPI);
            let predicted = run_h.max(def_h);
            let err = (predicted - com_gap).abs();
            total_err += err;
            max_err = max_err.max(err);
            assert!(
                err < 1.5,
                "{} {}pt: predicted={:.2}, COM={:.2}, err={:.2}",
                family, size, predicted, com_gap, err
            );
        }

        let avg_err = total_err / test_cases.len() as f32;
        assert!(avg_err < 0.5, "avg error {:.3}pt exceeds 0.5pt", avg_err);
    }
}
