/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const build_docx: (a: any) => [number, number, number, number];
export const build_docx_with_template: (a: any, b: number, c: number) => [number, number, number, number];
export const create_blank_docx: () => [number, number];
export const create_pdf: (a: number, b: number, c: number, d: number) => [number, number];
export const docx_to_pdf: (a: number, b: number) => [number, number, number, number];
export const edit_docx: (a: number, b: number, c: any) => [number, number, number, number];
export const edit_docx_advanced: (a: number, b: number, c: any) => [number, number, number, number];
export const edit_pptx: (a: number, b: number, c: any) => [number, number, number, number];
export const edit_text_and_relayout: (a: number, b: number, c: number, d: number) => [number, number, number];
export const edit_xlsx: (a: number, b: number, c: any) => [number, number, number, number];
export const edit_xlsx_from_workbook: (a: number, b: number, c: any) => [number, number, number, number];
export const format_cell_number: (a: number, b: number, c: number) => [number, number];
export const generate_hanko_svg: (a: any) => [number, number, number, number];
export const layout_document: (a: number, b: number) => [number, number, number];
export const list_spreadsheet_vba_procedures: (a: number, b: number) => [number, number, number];
export const parse_document: (a: number, b: number) => [number, number, number];
export const parse_pdf: (a: number, b: number) => [number, number, number];
export const parse_presentation: (a: number, b: number) => [number, number, number];
export const parse_spreadsheet: (a: number, b: number) => [number, number, number];
export const pdf_extract_text: (a: number, b: number) => [number, number, number, number];
export const pdf_verify_signatures: (a: number, b: number) => [number, number, number];
export const preview_hanko: (a: number, b: number) => [number, number];
export const run_spreadsheet_vba: (a: any, b: number, c: number, d: number, e: number, f: any, g: number) => [number, number, number];
export const set_docx_comments: (a: number, b: number, c: any) => [number, number, number, number];
export const update_docx_comments: (a: number, b: number, c: any) => [number, number, number, number];
export const init: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
